name: pythonCI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pylint
    - name: Analysing the code with pylint
      run: |
        pylint encoder/encoder/encode.py
    - name: Build package
      run: python -m build
    - name: Install locally to test
      run: python -m pip install ./dist/encodepacakge-0.0.7.tar.gz
    - name: Run unit test
      run: python ./test/test_encode.py
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
    - name: Install Pacakage from pypi
      run: python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ encodepacakge
      
      
